title: _min
author: underscoremin
email: underscoremin@proton.me
description: > # this means to ignore newlines until "show_excerpts:"
  Security Engineering -- Binary Exploitation -- Reverse Engineering -- OS Internals -- Programming.. I dibble dabble... 
show_excerpts: false # set to true to show excerpts on the homepage
domain: underscoremin.github.io
url: https://underscoremin.github.io/

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) disqus comment configuration
  disqus:
    shortname: underscoremin.github.io/

  # generate social links in footer
  # supported colours: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple

  # whether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # whether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: _min
  avatar_source: local
  avatar_path: /assets/avatar.png

# Build settings
remote_theme: no-style-please

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
